/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion;

import javax.swing.JOptionPane;
import org.itson.dominio.Producto;
import org.itson.implementaciones.FachadaNegocio;

/**
 *
 * @author Manuel Flores
 */
public class EditarProductosFrm extends javax.swing.JFrame {

    Producto productoEditar = null;
    FachadaNegocio fachada = new FachadaNegocio();
    
    /**
     * Creates new form EditarProductos
     */
    public EditarProductosFrm(Long id) {
        initComponents();
        this.cargarProducto(id);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public void mostrarEditarProducto(Long productoId){
        this.setVisible(true);
    }
    
    private void cargarProducto(Long productoId){
        try {
            productoEditar = fachada.getControlProducto().consultarProductoPorId(productoId);     
            tfNombre.setText(productoEditar.getNombre());
            tfPrecio.setText(Double.toString(productoEditar.getPrecio()));
            txaDesc.setText(productoEditar.getDescripcion());
        } catch (Exception e) {
        }
    }
    
    public void ocultarEditarProducto(){
        this.setVisible(false);
    }
    
    private void mostrarPantallaAdministrarProd(){
        AdministrarProductosFrm admin = new AdministrarProductosFrm();
        admin.mostrarPantallaAdminProductos();
        this.ocultarEditarProducto();
    }

    private void editarProducto() {
        try {
            if (tfNombre.getText().isEmpty() || tfNombre.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "\nNombre vacio o en blanco", "Error En la Operacion.", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txaDesc.getText().isEmpty() || txaDesc.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "\nDescripcion vacia o en blanco", "Error En la Operacion.", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (tfPrecio.getText().isEmpty() || tfPrecio.getText().isBlank() || !esNumeroValido(tfPrecio.getText())) {
                JOptionPane.showMessageDialog(null, "\nPrecio no valido", "Error En la Operacion.", JOptionPane.ERROR_MESSAGE);
                return;
            }
            productoEditar.setNombre(tfNombre.getText());
            productoEditar.setDescripcion(txaDesc.getText());
            productoEditar.setPrecio(Double.parseDouble(tfPrecio.getText()));
            fachada.getControlProducto().actualizarProducto(productoEditar);
            JOptionPane.showMessageDialog(null, "\nProducto actualizado correctamente", "Producto actualizado", JOptionPane.INFORMATION_MESSAGE);
            this.mostrarPantallaAdministrarProd();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "\nError al actualizar en la base de datos", "Error En la Operacion.", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public boolean esNumeroValido(String texto) {
        try {
            Double.parseDouble(texto); 
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        spDesc = new javax.swing.JScrollPane();
        txaDesc = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        lblDesc1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 64)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Editar producto");

        lblDesc.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDesc.setText("Descripción del producto");

        lblNombre.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre del producto");

        tfPrecio.setBackground(new java.awt.Color(255, 255, 255));
        tfPrecio.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        tfPrecio.setForeground(new java.awt.Color(0, 0, 0));
        tfPrecio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tfNombre.setBackground(new java.awt.Color(255, 255, 255));
        tfNombre.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(0, 0, 0));
        tfNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txaDesc.setBackground(new java.awt.Color(255, 255, 255));
        txaDesc.setColumns(20);
        txaDesc.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        txaDesc.setForeground(new java.awt.Color(0, 0, 0));
        txaDesc.setRows(5);
        txaDesc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        spDesc.setViewportView(txaDesc);

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("<");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblDesc1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblDesc1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDesc1.setText("Precio");

        btnEditar.setBackground(new java.awt.Color(102, 255, 102));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar producto");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(618, 618, 618)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesc1)
                            .addComponent(lblDesc)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNombre)
                                .addComponent(tfNombre)
                                .addComponent(spDesc)
                                .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGap(75, 75, 75)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblDesc)
                .addGap(31, 31, 31)
                .addComponent(spDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblDesc1)
                .addGap(27, 27, 27)
                .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.mostrarPantallaAdministrarProd();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.editarProducto();
    }//GEN-LAST:event_btnEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDesc1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane spDesc;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextArea txaDesc;
    // End of variables declaration//GEN-END:variables
}
